### ISSUE TITLE
Carddav support while installing Roundcube app

### ISSUE THREAD

**Issue by julpec** [YunoHost/moulinette-yunohost#62]
Hello

It's not possible to choose to link Roundcube (RC) with Baikal for the user adressbook. At this moment, the only way to do this is to wait the RC app update.
Indeed, it's necessary to install Baikal **before** RC.

For instance, it should be interesting to show a popup notification while installing RC. This notification should present the goal to install Baikal before RC to get the benefice of managing carddav through RC. The user could ignore it or could have a direct link to the Baikal App installation.

Nice ?

**Comment by julienmalik** [comment]
I think we don't want to provide specific functionalities for dependencies between apps, because this is a tricky road, and the use case is limited (we don't have many dependencies today and that's good).

That said, having a TXT field in the manifest for a pre-install message would be nice. Might be simple enough to implement and cover this use case.
This message could be displayed in the cli, maybe with waiting for user input before proceeding to the installation parameter ("Do you want to continue installation ? [Y/n]").
Could also be displayed in the admin web-ui, pop-up or something else.

**Comment by opi** [comment]
Agreed. App dependencies is not the way yunohost is built. Except now for these {card|cal}dav thing, and it's not working perfectly.

Do we keep this issue open, and create another issue for "pre-install message" during app installation ? (in moulinette and admin repositories)

**Comment by jeromelebleu** [comment]
Agreed too. I think it should be specified from the application package - i.e. in the doc for the app, in a new "notice" manifest key.

Moreover, I think this issue can be related to https://github.com/YunoHost/moulinette-yunohost/issues/53. When it will be implemented, it will simulate something like a "manual reinstallation", allowing the user to have {Card|Cal}Dav support in RoundCube if Baikal is installed just before.

@opi for the "pre-install message" idea, I've created a new issue here: https://github.com/YunoHost/moulinette-yunohost/issues/72, so feel free to give your opinion! :)
